import { diaryDate, occurrenceLabels, weatherLabels, type DiaryEntry, type DiaryPhoto } from "@/lib/diary";

export function escapeHtml(value: string | number) {
  return String(value).replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!);
}

export function diaryReportHtml(organization: string, entries: (DiaryEntry & { photos: DiaryPhoto[] })[], generatedAt: string, nonce: string) {
  const e = escapeHtml;
  return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Diário de obra · ${e(organization)}</title>
  <style>body{font:16px/1.6 system-ui,sans-serif;color:#12243c;background:#edf2f8;margin:0;padding:24px}main{max-width:980px;margin:auto}header,article{padding:28px;background:white;border:1px solid #d8e1ed;border-radius:16px;margin-bottom:20px}header{border-top:6px solid #0ab4c7}h1{margin:0;font-size:28px}h2{font-size:22px;margin:0}h3{font-size:16px;margin:20px 0 4px}.meta{font-size:14px;color:#52637a}.text{white-space:pre-wrap;overflow-wrap:anywhere}.photos{display:grid;grid-template-columns:1fr 1fr;gap:16px}figure{margin:0;break-inside:avoid}img{width:100%;height:240px;object-fit:contain;background:#f4f7fb}figcaption{font-size:14px;overflow-wrap:anywhere}button{padding:12px 18px;background:#1858e8;color:white;border:0;border-radius:9px;font:inherit;cursor:pointer}details{font-size:12px;overflow-wrap:anywhere}@media(max-width:600px){body{padding:12px}header,article{padding:18px}.photos{grid-template-columns:1fr}}@media print{body{padding:0;background:white}header,article{border:0;padding:0;border-radius:0}article{break-before:page}button{display:none}h2,h3{break-after:avoid}p{orphans:3;widows:3}details{display:block}.photos img{height:200px}@page{size:A4;margin:16mm}}</style></head>
  <body><main><header><p class="meta">H.OIKOS · ${e(organization)}</p><h1>Diário de obra</h1><p>${entries.length} registro(s) · Emitido em ${e(generatedAt)}</p><p class="meta">Versões atuais do período e filtros selecionados. Autoria e horários são registros da plataforma; este relatório não contém assinatura digital certificada.</p><button id="print">Imprimir / salvar PDF</button></header>
  ${entries.map((entry) => `<article><p class="meta">${e(entry.projectCode)} · ${e(entry.projectName)}</p><h2>${e(diaryDate(entry.entryDate))} · Registro de obra</h2><p class="meta">Autor: ${e(entry.authorName)} · Revisão ${entry.revision}<br>Registrado em ${e(entry.createdAt)} UTC · Atualizado em ${e(entry.updatedAt)} UTC<br>ID: ${e(entry.id)}</p><p>Clima: ${e(weatherLabels[entry.weather] ?? entry.weather)} · Equipe no local: ${entry.workforceCount}</p><h3>Atividades executadas</h3><p class="text">${e(entry.summary)}</p><h3>Ocorrências · ${e(occurrenceLabels[entry.occurrenceType])}</h3><p class="text">${e(entry.blockers || "Nenhuma ocorrência informada.")}</p>${entry.photos.length ? `<h3>Registro fotográfico</h3><div class="photos">${entry.photos.map((photo) => `<figure><img src="${e(photo.url)}" alt="${e(photo.caption || photo.name)}"><figcaption>${e(photo.caption || photo.name)}<br><span class="meta">Enviado por ${e(photo.uploadedByName)} · ${e(photo.createdAt)} UTC</span><details><summary>Identificação da foto</summary>ID ${e(photo.id)} · SHA-256 ${e(photo.sha256)}</details></figcaption></figure>`).join("")}</div>` : "<p class=\"meta\">Sem fotos anexadas.</p>"}</article>`).join("")}</main><script nonce="${e(nonce)}">document.getElementById('print').addEventListener('click',()=>window.print());</script></body></html>`;
}
