"use client";
import Link from "next/link";
import { type FormEvent, useRef, useState } from "react";
import { ClipboardCheck, Copy, ExternalLink, LoaderCircle, Plus, RefreshCw, Settings2, UserPlus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Empty, EmptyHeader, EmptyTitle, EmptyDescription } from "@/components/ui/empty";
import { Skeleton } from "@/components/ui/skeleton";
import { PortalError, PortalItemCard } from "@/components/portal-shared";
import { resourceJson, resourceMessage, useLiveResource } from "@/hooks/use-live-resource";
import type { PortalAccess, PortalItem, PortalPage, PortalProject } from "@/lib/portal";
import type { DiaryDetail, DiaryEntry } from "@/lib/diary";
import { diaryDate } from "@/lib/diary";

type AccessData = { accesses: PortalAccess[]; projects: PortalProject[] };
export function PortalManager({ canEdit, canManage, canReadDiary, projectId }: { canEdit: boolean; canManage: boolean; canReadDiary: boolean; projectId?: string }) {
  const resource = useLiveResource<AccessData>("/api/portal-management/access");
  const [selectedId, setSelectedId] = useState(""); const [page, setPage] = useState(1);
  const accesses = (resource.data?.accesses ?? []).filter((access) => !projectId || access.projectId === projectId);
  const selected = accesses.find((access) => access.id === selectedId) ?? accesses[0];
  const items = useLiveResource<PortalPage>(selected ? `/api/portal-management/items?accessId=${selected.id}&page=${page}` : null);
  const [mode, setMode] = useState<"invite" | "settings" | "publish" | null>(null);
  const [link, setLink] = useState(""); const [copyState, setCopyState] = useState("");
  const [withdraw, setWithdraw] = useState<PortalItem | null>(null);
  function changed(result?: { access: PortalAccess; invitationUrl?: string | null }) {
    if (result?.invitationUrl) { setLink(result.invitationUrl); setCopyState(""); }
    if (result?.access) setSelectedId(result.access.id);
    setMode(null); resource.refresh(); items.refresh();
  }
  return <section className="space-y-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><h2 className="display-heading flex items-center gap-3 text-3xl"><span className="grid size-11 place-items-center rounded-md bg-primary text-hoikos-300"><ClipboardCheck className="size-5" /></span>Portal do cliente</h2><p className="mt-2 text-sm text-hoikos-500">Compartilhe o andamento e solicite decisões sem abrir os dados internos.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" aria-label="Atualizar portal" onClick={() => { resource.refresh(); items.refresh(); }}><RefreshCw className="size-4" /></Button><Button asChild variant="outline"><Link href="/portal" target="_blank"><ExternalLink className="size-4" />Área do cliente</Link></Button>{canManage && <Button disabled={!resource.data?.projects.length || Boolean(resource.error)} onClick={() => setMode("invite")}><UserPlus className="size-4" />Convidar cliente</Button>}</div></div>
    {resource.error && <PortalError message={resource.error} retry={resource.refresh} />}
    {link && <Card className="border-hoikos-200 bg-hoikos-50"><CardContent className="space-y-3 p-4"><p className="font-medium">Convite pronto para enviar</p><p className="text-sm text-hoikos-600">Válido por 7 dias e vinculado ao e-mail informado. Copie e envie ao destinatário; nenhum e-mail foi enviado automaticamente.</p><div className="flex flex-col gap-2 sm:flex-row"><Input aria-label="Link do convite do cliente" readOnly value={link} className="min-w-0 bg-white" /><Button variant="outline" onClick={async () => { try { await navigator.clipboard.writeText(link); setCopyState("Link copiado."); } catch { setCopyState("Selecione e copie o link acima."); } }}><Copy className="size-4" />Copiar link</Button><Button variant="ghost" onClick={() => setLink("")}>Ocultar</Button></div><p aria-live="polite" className="text-sm">{copyState}</p></CardContent></Card>}
    {resource.loading ? <Skeleton className="h-60 rounded-md" /> : selected ? <>
      <Card className="border-border"><CardContent className="space-y-4 p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-end"><div className="min-w-0 flex-1 space-y-2"><Label htmlFor="portal-access-select">Cliente e obra</Label><Select value={selected.id} onValueChange={(id) => { setSelectedId(id); setPage(1); }}><SelectTrigger id="portal-access-select" className="w-full"><SelectValue /></SelectTrigger><SelectContent>{accesses.map((access) => <SelectItem key={access.id} value={access.id}>{access.name} · {access.projectName}</SelectItem>)}</SelectContent></Select></div>{canManage && <Button variant="outline" disabled={Boolean(resource.error)} onClick={() => setMode("settings")}><Settings2 className="size-4" />Gerenciar acesso</Button>}</div><div className="flex flex-wrap gap-3 text-sm"><Badge variant="outline" className={selected.status === "active" ? "border-hoikos-200 bg-hoikos-50 text-hoikos-800" : "bg-hoikos-50"}>{selected.status === "active" ? "Ativo" : selected.status === "revoked" ? "Revogado" : selected.expiresAt < (resource.updatedAt?.getTime() ?? 0) ? "Convite expirado" : "Aguardando aceite"}</Badge><p className="break-all text-hoikos-500">{selected.email}</p><p className="text-hoikos-500">Andamento: {selected.viewProgress ? "liberado" : "oculto"} · Aprovações: {selected.canApprove ? "liberadas" : "somente leitura"}</p></div><p className="text-sm text-hoikos-500">Somente os itens enviados para este acesso são exibidos ao destinatário. Diário e novas fotos não são compartilhados automaticamente.</p></CardContent></Card>
      <div className="flex flex-wrap items-center justify-between gap-3"><h3 className="text-xl font-semibold">Conteúdo e decisões {items.data?.pending ? `· ${items.data.pending} pendente(s)` : ""}</h3>{canEdit && <Button disabled={selected.status === "revoked" || Boolean(resource.error)} onClick={() => setMode("publish")}><Plus className="size-4" />Compartilhar / pedir aprovação</Button>}</div>
      {items.error && <PortalError message={items.error} retry={items.refresh} />}{items.loading ? <Skeleton className="h-64 rounded-md" /> : items.data?.items.map((item) => <PortalItemCard key={item.id} item={item}>{canEdit && item.status === "open" && <Button variant="outline" disabled={Boolean(items.error)} onClick={() => setWithdraw(item)}>Retirar do portal</Button>}</PortalItemCard>)}
      {items.data && !items.data.items.length && <Card><Empty><EmptyHeader><EmptyTitle>Nenhum conteúdo compartilhado</EmptyTitle><EmptyDescription>Envie uma atualização ou solicitação de aprovação. O cliente não verá anotações internas da equipe.</EmptyDescription></EmptyHeader></Empty></Card>}
      {items.data && items.data.total > items.data.pageSize && <div className="flex items-center justify-end gap-3"><Button variant="outline" disabled={page <= 1} onClick={() => setPage((value) => value - 1)}>Anterior</Button><p className="text-sm">Página {page} de {Math.ceil(items.data.total / items.data.pageSize)}</p><Button variant="outline" disabled={page * items.data.pageSize >= items.data.total} onClick={() => setPage((value) => value + 1)}>Próxima</Button></div>}
    </> : !resource.error && <Card><Empty><EmptyHeader><EmptyTitle>Nenhum cliente com acesso ao portal</EmptyTitle><EmptyDescription>{resource.data?.projects.length ? "Convide o cliente para uma obra e defina se ele pode acompanhar o andamento e responder aprovações." : "Cadastre uma obra e libere Projetos e obras para criar o primeiro convite."}</EmptyDescription></EmptyHeader></Empty></Card>}
    {mode === "invite" && <AccessDialog projects={resource.data?.projects ?? []} projectId={projectId} onClose={() => setMode(null)} onSaved={changed} />}
    {mode === "settings" && selected && <AccessDialog key={selected.id} current={selected} projects={resource.data?.projects ?? []} onClose={() => setMode(null)} onSaved={changed} />}
    {mode === "publish" && selected && <PublishDialog access={selected} canReadDiary={canReadDiary} onClose={() => setMode(null)} onSaved={() => changed()} />}
    {withdraw && <WithdrawDialog item={withdraw} onClose={() => setWithdraw(null)} onSaved={() => { setWithdraw(null); items.refresh(); }} />}
    <p className="text-xs text-hoikos-500">Atualização a cada 15 segundos. Decisões são registros de aceite na plataforma, não assinaturas digitais certificadas.</p>
  </section>;
}

function AccessDialog({ current, projects, projectId, onClose, onSaved }: { current?: PortalAccess; projects: PortalProject[]; projectId?: string; onClose: () => void; onSaved: (result: { access: PortalAccess; invitationUrl?: string | null }) => void }) {
  const [project, setProject] = useState(current?.projectId ?? projectId ?? ""); const [name, setName] = useState(current?.name ?? ""); const [email, setEmail] = useState(current?.email ?? "");
  const [viewProgress, setViewProgress] = useState(current?.viewProgress ?? true); const [canApprove, setCanApprove] = useState(current?.canApprove ?? false);
  const [action, setAction] = useState("permissions"); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const submitting = useRef(false);
  async function submit(event: FormEvent) {
    event.preventDefault(); if (submitting.current) return; submitting.current = true; setBusy(true); setError("");
    try { onSaved(await resourceJson(current ? `/api/portal-management/access/${current.id}` : "/api/portal-management/access", { method: current ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(current ? { revision: current.revision, action, viewProgress, canApprove } : { projectId: project, name, email, viewProgress, canApprove }) })); }
    catch (cause) { setError(resourceMessage(cause)); } finally { submitting.current = false; setBusy(false); }
  }
  return <Dialog open onOpenChange={(open) => { if (!open && !busy) onClose(); }}><DialogContent className="max-h-[90svh] overflow-y-auto"><DialogHeader><DialogTitle>{current ? "Gerenciar acesso do cliente" : "Convidar cliente"}</DialogTitle><DialogDescription>{current ? `${current.name} · ${current.projectName}` : "O convite libera somente esta obra para o e-mail indicado."}</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-4"><fieldset disabled={busy} className="space-y-4">{!current ? <><div className="space-y-2"><Label htmlFor="portal-project">Obra / projeto</Label><Select value={project} onValueChange={setProject} disabled={Boolean(projectId)}><SelectTrigger id="portal-project" className="w-full"><SelectValue placeholder="Selecione a obra" /></SelectTrigger><SelectContent>{projects.map((item) => <SelectItem key={item.id} value={item.id}>{item.code} · {item.name}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label htmlFor="portal-name">Nome do cliente</Label><Input id="portal-name" value={name} onChange={(event) => setName(event.target.value)} required minLength={2} maxLength={120} /></div><div className="space-y-2"><Label htmlFor="portal-email">E-mail do acesso</Label><Input id="portal-email" type="email" value={email} onChange={(event) => setEmail(event.target.value)} required maxLength={160} /></div></> : <div className="space-y-2"><Label htmlFor="portal-action">O que deseja fazer?</Label><Select value={action} onValueChange={setAction}><SelectTrigger id="portal-action" className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="permissions">Alterar permissões</SelectItem><SelectItem value="renew">Renovar convite</SelectItem><SelectItem value="revoke">Revogar acesso</SelectItem></SelectContent></Select></div>}
    {(!current || action === "permissions") && <div className="space-y-3 rounded-md bg-hoikos-50 p-4"><div className="flex gap-3"><Checkbox id="portal-view-progress" checked={viewProgress} onCheckedChange={(value) => setViewProgress(value === true)} /><Label htmlFor="portal-view-progress" className="block leading-6">Ver andamento, fase e datas da obra</Label></div><div className="flex gap-3"><Checkbox id="portal-can-approve" checked={canApprove} onCheckedChange={(value) => setCanApprove(value === true)} /><Label htmlFor="portal-can-approve" className="block leading-6">Responder solicitações de aprovação</Label></div></div>}
    {current && action === "renew" && <p className="text-sm text-hoikos-800">O link anterior será invalidado e o acesso ficará suspenso até o cliente aceitar o novo convite. As decisões anteriores permanecem no histórico.</p>}{current && action === "revoke" && <p className="text-sm text-hoikos-800">Este cliente deixará de acessar a obra, os conteúdos e as fotos. O histórico de decisões será preservado.</p>}</fieldset>{error && <PortalError message={error} />}<Button type="submit" disabled={busy || !project} className="w-full">{busy && <LoaderCircle className="size-4 animate-spin" />}{current ? action === "revoke" ? "Revogar acesso" : action === "renew" ? "Gerar novo convite" : "Salvar permissões" : "Criar convite"}</Button></form></DialogContent></Dialog>;
}

function PublishDialog({ access, canReadDiary, onClose, onSaved }: { access: PortalAccess; canReadDiary: boolean; onClose: () => void; onSaved: () => void }) {
  const [id] = useState(() => crypto.randomUUID()); const [kind, setKind] = useState("update"); const [title, setTitle] = useState(""); const [body, setBody] = useState(""); const [dueDate, setDueDate] = useState("");
  const [source, setSource] = useState("none"); const [diaryPage, setDiaryPage] = useState(1); const [photoIds, setPhotoIds] = useState<string[]>([]); const [confirmed, setConfirmed] = useState(false);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const submitting = useRef(false);
  const diaries = useLiveResource<{ entries: DiaryEntry[]; total: number; pageSize: number }>(canReadDiary ? `/api/diary?projectId=${access.projectId}&page=${diaryPage}` : null, 0);
  const detail = useLiveResource<DiaryDetail>(source !== "none" ? `/api/diary/${source}` : null, 0);
  async function submit(event: FormEvent) {
    event.preventDefault(); if (submitting.current) return; submitting.current = true; setBusy(true); setError("");
    try { await resourceJson("/api/portal-management/items", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, accessId: access.id, kind, title, body, dueDate: kind === "approval" && dueDate ? dueDate : null, sourceDiaryId: source === "none" ? null : source, photoIds }) }); onSaved(); }
    catch (cause) { setError(resourceMessage(cause)); } finally { submitting.current = false; setBusy(false); }
  }
  return <Dialog open onOpenChange={(open) => { if (!open && !busy) onClose(); }}><DialogContent className="max-h-[90svh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Compartilhar com {access.name}</DialogTitle><DialogDescription>{access.projectName} · O texto e as fotos selecionadas serão disponibilizados apenas neste acesso.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-4"><fieldset disabled={busy} className="space-y-4"><div className="space-y-2"><Label htmlFor="portal-kind">Tipo de envio</Label><Select value={kind} onValueChange={(value) => { setKind(value); setConfirmed(false); }}><SelectTrigger id="portal-kind" className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="update">Atualização da obra</SelectItem><SelectItem value="approval" disabled={!access.canApprove}>Solicitação de aprovação</SelectItem></SelectContent></Select></div>
    {canReadDiary && <details className="rounded-md border border-hoikos-200 p-4"><summary className="cursor-pointer text-sm font-medium">Usar um registro do diário (opcional)</summary><div className="mt-4 space-y-3">{diaries.error && <PortalError message={diaries.error} retry={diaries.refresh} />}<Label htmlFor="portal-source">Registro de origem</Label><Select value={source} onValueChange={(value) => { setSource(value); setPhotoIds([]); setConfirmed(false); }}><SelectTrigger id="portal-source" className="w-full"><SelectValue placeholder="Selecione o registro" /></SelectTrigger><SelectContent><SelectItem value="none">Sem vínculo com diário</SelectItem>{diaries.data?.entries.map((entry) => <SelectItem key={entry.id} value={entry.id}>{diaryDate(entry.entryDate)} · {entry.summary.slice(0, 60)}</SelectItem>)}</SelectContent></Select>{diaries.data && diaries.data.total > diaries.data.pageSize && <div className="flex gap-2"><Button type="button" variant="outline" size="sm" disabled={diaryPage <= 1} onClick={() => setDiaryPage((value) => value - 1)}>Mais recentes</Button><Button type="button" variant="outline" size="sm" disabled={diaryPage * diaries.data.pageSize >= diaries.data.total} onClick={() => setDiaryPage((value) => value + 1)}>Mais antigos</Button></div>}{detail.error && <PortalError message={detail.error} retry={detail.refresh} />}{detail.data && <><p className="text-sm text-hoikos-500">O histórico interno não será compartilhado. Revise o texto antes de enviar.</p><Button type="button" variant="outline" onClick={() => { setTitle(`Atualização da obra · ${diaryDate(detail.data!.entry.entryDate)}`); setBody(detail.data!.entry.summary); setConfirmed(false); }}>Copiar atividades para o texto</Button><div className="space-y-2">{detail.data.photos.map((photo) => <div key={photo.id} className="flex items-start gap-2"><Checkbox id={`share-${photo.id}`} checked={photoIds.includes(photo.id)} onCheckedChange={(value) => { setPhotoIds((current) => value === true ? [...current, photo.id] : current.filter((id) => id !== photo.id)); setConfirmed(false); }} /><Label htmlFor={`share-${photo.id}`} className="block break-words leading-6">{photo.caption || photo.name}</Label><a href={photo.url} target="_blank" rel="noopener noreferrer" className="ml-auto text-sm text-hoikos-700 underline">Ver</a></div>)}</div></>}</div></details>}
    <div className="space-y-2"><Label htmlFor="portal-title">Título</Label><Input id="portal-title" required minLength={3} maxLength={160} value={title} onChange={(event) => { setTitle(event.target.value); setConfirmed(false); }} /></div><div className="space-y-2"><Label htmlFor="portal-body">Conteúdo que o cliente verá</Label><Textarea id="portal-body" required minLength={3} maxLength={10000} rows={6} value={body} onChange={(event) => { setBody(event.target.value); setConfirmed(false); }} placeholder="Informe os avanços ou descreva exatamente o que precisa de aprovação." /></div>{kind === "approval" && <div className="space-y-2"><Label htmlFor="portal-due">Data solicitada para resposta (opcional)</Label><Input id="portal-due" type="date" value={dueDate} onChange={(event) => { setDueDate(event.target.value); setConfirmed(false); }} /></div>}<div className="flex items-start gap-3 rounded-md bg-hoikos-50 p-4"><Checkbox id="portal-publish-confirm" checked={confirmed} onCheckedChange={(value) => setConfirmed(value === true)} /><Label htmlFor="portal-publish-confirm" className="block leading-6">Revisei o texto e as {photoIds.length} foto(s) selecionada(s). Autorizo compartilhar com {access.email}.</Label></div><p className="text-xs text-hoikos-500">O conteúdo enviado não é editado retroativamente. Para corrigir uma solicitação pendente, retire-a e publique uma nova.</p></fieldset>{error && <PortalError message={error} />}<Button type="submit" disabled={busy || !confirmed || detail.loading || Boolean(detail.error)} className="w-full">{busy && <LoaderCircle className="size-4 animate-spin" />}Compartilhar no portal</Button></form></DialogContent></Dialog>;
}

function WithdrawDialog({ item, onClose, onSaved }: { item: PortalItem; onClose: () => void; onSaved: () => void }) {
  const [reason, setReason] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { await resourceJson(`/api/portal-management/items/${item.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ accessId: item.accessId, reason }) }); onSaved(); } catch (cause) { setError(resourceMessage(cause)); } finally { setBusy(false); } }
  return <Dialog open onOpenChange={(open) => { if (!open && !busy) onClose(); }}><DialogContent><DialogHeader><DialogTitle>Retirar item do portal</DialogTitle><DialogDescription>{item.title}. O cliente verá a retirada e seu motivo. Um item já respondido não pode ser retirado.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-4"><Label htmlFor="portal-withdraw-reason">Motivo</Label><Textarea id="portal-withdraw-reason" required minLength={5} maxLength={500} value={reason} disabled={busy} onChange={(event) => setReason(event.target.value)} />{error && <PortalError message={error} />}<Button type="submit" disabled={busy}>{busy && <LoaderCircle className="size-4 animate-spin" />}Confirmar retirada</Button></form></DialogContent></Dialog>;
}
