import { apiRoute, ensureFound, requireModulePermission, requireOrganizationContext } from "@/lib/server/backend";
import { budgetSelect, type BudgetRow } from "@/lib/server/budgets-records";
export const dynamic = "force-dynamic";
const escape = (value: unknown) => String(value ?? "").replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);
const money = (cents: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(cents / 100);
export async function GET(request: Request, route: { params: Promise<{ budgetId: string }> }) {
  return apiRoute(async () => {
    const context = await requireOrganizationContext(request); requireModulePermission(context, "budgets", "view");
    const { budgetId } = await route.params;
    const budget = ensureFound(await context.db.prepare(`${budgetSelect} WHERE b.id = ?1 AND b.organization_id = ?2`).bind(budgetId, context.organization.id).first<BudgetRow>(), "Orçamento");
    const items = await context.db.prepare("SELECT description, unit, quantity, unit_price_cents FROM budget_items WHERE budget_version_id = ?1 ORDER BY sort_order").bind(budgetId).all<{ description: string; unit: string; quantity: number; unit_price_cents: number }>();
    const status = { draft: "Rascunho", sent: "Enviado", approved: "Aprovação registrada", rejected: "Recusado", archived: "Arquivado" }[budget.status] ?? budget.status;
    return new Response(`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Orçamento ${escape(budget.code)}</title><style>body{font:14px Arial,sans-serif;color:#1c190f;max-width:960px;margin:32px auto;padding:24px}h1{font-size:28px}table{width:100%;border-collapse:collapse;margin:24px 0}th,td{padding:10px;border-bottom:1px solid #ccc;text-align:left}td:nth-child(n+3),th:nth-child(n+3){text-align:right}thead{display:table-header-group}tr{break-inside:avoid}.total{text-align:right;font-size:20px}.hint{padding:12px;background:#f4f2e9}@media print{body{margin:0;padding:0}.hint{display:none}@page{size:A4;margin:18mm}}</style></head><body><p class="hint">Use Imprimir no navegador (Ctrl+P) para salvar como PDF.</p><p>H.OIKOS · ${escape(context.organization.name)}</p><h1>Orçamento ${escape(budget.code)} · v${budget.version}</h1><p>${escape(budget.project_name)} · ${escape(status)}</p><table><thead><tr><th>Descrição</th><th>Unidade</th><th>Quantidade</th><th>Preço unitário</th><th>Total</th></tr></thead><tbody>${items.results.map(item => `<tr><td>${escape(item.description)}</td><td>${escape(item.unit)}</td><td>${escape(item.quantity.toLocaleString("pt-BR"))}</td><td>${escape(money(item.unit_price_cents))}</td><td>${escape(money(Math.round(item.quantity * item.unit_price_cents)))}</td></tr>`).join("")}</tbody></table><p class="total">Total: <strong>${escape(money(budget.total_cents))}</strong></p><p>Emitido em ${new Date().toLocaleDateString("pt-BR")}. O registro de situação nesta plataforma não substitui a manifestação de aceite do cliente.</p></body></html>`, { headers: { "Content-Type": "text/html; charset=utf-8", "Cache-Control": "private, no-store", "X-Content-Type-Options": "nosniff", "Content-Security-Policy": "default-src 'none'; style-src 'unsafe-inline'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'" } });
  });
}
